# Generated by Django 5.0.6 on 2024-06-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zoo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kiosk",
            name="name",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
    ]
