# Generated by Django 5.0.6 on 2024-08-22 07:39

import datetime
import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaspi', '0003_alter_magazine_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='reserving',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(default=(datetime.datetime(2024, 8, 22, 12, 39, 36, 300377), '2024-12-31'), verbose_name='Reserving time'),
        ),
    ]
